<?php

return [
    'weight_names' => [
        'glitches_required' => 'glitches',
        'item_placement' => 'item_placement',
        'dungeon_items' => 'dungeon_items',
        'boss_items' => 'boss_items',
        'drop_shuffle' => 'drop_shuffle',
        'bonk_shuffle' => 'bonk_shuffle',
        'pottery_shuffle' => 'pottery_shuffle',
        'accessibility' => 'accessibility',
        'goal' => 'goal',
        'tower_open' => 'crystals.tower',
        'ganon_open' => 'crystals.ganon',
        'ganon_item' => 'ganon_item',
        'world_state' => 'mode',
        'entrance_shuffle' => 'entrances',
        'door_shuffle' => 'doors.shuffle',
        'door_intensity' => 'doors.intensity',
        'door_type_mode' => 'doors.type_mode',
        'trap_door_mode' => 'doors.trap_mode',
        'decouple_doors' => 'doors.decoupled',
        'ow_shuffle' => 'overworld.shuffle',
        'ow_crossed' => 'overworld.crossed',
        'ow_keep_similar' => 'overworld.keep_similar',
        'ow_mixed' => 'overworld.mixed',
        'flute_shuffle' => 'overworld.flute_shuffle',
        'whirlpool_shuffle' => 'overworld.whirlpool_shuffle',
        'shop_shuffle' => 'shopsanity',
        'boss_shuffle' => 'enemizer.boss_shuffle',
        'enemy_shuffle' => 'enemizer.enemy_shuffle',
        'enemy_damage' => 'enemizer.enemy_damage',
        'enemy_health' => 'enemizer.enemy_health',
        'hints' => 'hints',
        'weapons' => 'weapons',
        'item_pool' => 'item.pool',
        'item_functionality' => 'item.functionality',
        'starting_flute' => 'equipment.flute',
        'starting_boots' => 'equipment.boots',
    ],
];
